import { createCipheriv, createDecipheriv, randomBytes } from 'crypto';

// ─── Secret vault (envelope encryption) ───────────────────────────────────────
// All anchor secret seeds and vendor credentials are encrypted at rest with a
// single master key-encryption-key (KEK) supplied via env. This replaces the old
// plaintext `tenant_keypairs.secret_key` column (DL-007).
//
// MASTER_KEK must be a 32-byte key, base64-encoded. In dev it is generated by
// scripts/setup-base.mjs. In production this belongs in a KMS/HSM — see DL-007.
//
// NOTE: losing MASTER_KEK makes every stored secret unrecoverable. On testnet
// that only means re-provisioning anchors, which is acceptable.

const ALGO = 'aes-256-gcm';
const IV_BYTES = 12; // GCM standard nonce length

let cachedKey: Buffer | null = null;

function kek(): Buffer {
  if (cachedKey) return cachedKey;
  const raw = process.env.MASTER_KEK;
  if (!raw) {
    throw new Error('MASTER_KEK not set — cannot encrypt/decrypt secrets. Run scripts/setup-base.mjs.');
  }
  const key = Buffer.from(raw, 'base64');
  if (key.length !== 32) {
    throw new Error(`MASTER_KEK must decode to 32 bytes (got ${key.length}). Regenerate it.`);
  }
  cachedKey = key;
  return key;
}

export interface SealedSecret {
  ciphertext: string; // base64
  iv: string;         // base64
  tag: string;        // base64 (GCM auth tag)
}

export function encryptSecret(plaintext: string): SealedSecret {
  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv(ALGO, kek(), iv);
  const enc = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();
  return {
    ciphertext: enc.toString('base64'),
    iv: iv.toString('base64'),
    tag: tag.toString('base64'),
  };
}

export function decryptSecret(sealed: SealedSecret): string {
  const decipher = createDecipheriv(ALGO, kek(), Buffer.from(sealed.iv, 'base64'));
  decipher.setAuthTag(Buffer.from(sealed.tag, 'base64'));
  const dec = Buffer.concat([
    decipher.update(Buffer.from(sealed.ciphertext, 'base64')),
    decipher.final(),
  ]);
  return dec.toString('utf8');
}
