apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cell-bootstrap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kaushik2003/nordstern.git
    targetRevision: HEAD
    path: anchor-template/infra/argocd/bootstrap-stack
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
