/**
 * Base-stack setup for the anchor factory (DL-005/DL-006).
 * Generates .env.base with the master key-encryption-key, JWT secret, and the
 * host path for per-anchor generated configs. Per-anchor keypairs/assets are NO
 * longer generated here — the control-plane provisions those on demand.
 *
 * Run once: node scripts/setup-base.mjs
 */

import { randomBytes } from 'crypto';
import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env.base');
const CONFIG_DIR = path.join(ROOT, 'anchor-configs');

if (existsSync(ENV_PATH)) {
  console.error('ERROR: .env.base already exists. Delete it manually if you want to reset.');
  process.exit(1);
}

// Master KEK: 32 random bytes, base64. Losing this makes stored secrets
// unrecoverable — on testnet that only means re-provisioning anchors.
const masterKek = randomBytes(32).toString('base64');
const cpJwt     = randomBytes(24).toString('base64');

mkdirSync(CONFIG_DIR, { recursive: true });

const env = `# Base-stack env for the anchor factory — generated by scripts/setup-base.mjs.
# Secrets: do NOT commit this file.
MASTER_KEK=${masterKek}
CP_JWT_SECRET=${cpJwt}
ANCHOR_CONFIG_HOST_ROOT=${CONFIG_DIR}

# surepass sandbox (optional — fill SUREPASS_TOKEN to use real KYC).
SUREPASS_BASE_URL=https://sandbox.surepass.io
SUREPASS_TOKEN=
`;

writeFileSync(ENV_PATH, env);
console.log('=== Anchor factory — base setup ===\n');
console.log(`  Wrote ${ENV_PATH}`);
console.log(`  Config dir: ${CONFIG_DIR}`);
console.log('\nNext: ./scripts/dev.sh');
