/**
 * NordStern Anchor Template — testnet setup.
 *
 * Unlike a mint-your-own-token anchor, this anchor does NOT issue USDC — Circle
 * does. So we generate only two keypairs:
 *   • signing  — SEP-10 home-domain signing key (AP: SECRET_SEP10_SIGNING_SEED)
 *   • treasury — holds the USDC FLOAT (AP asset `distribution_account`)
 *
 * Steps: generate keys → fund both with XLM via Friendbot → add a USDC trustline
 * to the treasury (so it can hold USDC) → render config/{stellar.toml,assets.yaml}
 * from templates → write .env. Funding the USDC float itself is Phase B (there is
 * no Friendbot for USDC).
 *
 * Run once:  node scripts/setup-testnet.mjs
 */

import {
  Keypair, Networks, Horizon, TransactionBuilder, BASE_FEE, Operation, Asset,
} from '@stellar/stellar-sdk';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { randomBytes } from 'crypto';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname   = path.dirname(fileURLToPath(import.meta.url));
const ROOT        = path.join(__dirname, '..');
const CONFIG_DIR  = path.join(ROOT, 'config');

const ASSET_CODE        = 'USDC';
const USDC_ISSUER       = 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5'; // Circle testnet USDC
const HORIZON_URL       = 'https://horizon-testnet.stellar.org';
const FRIENDBOT_URL     = 'https://friendbot.stellar.org';
const NETWORK_PASSPHRASE = Networks.TESTNET;

const server = new Horizon.Server(HORIZON_URL);
const rand = () => randomBytes(32).toString('base64url');

// Guard — re-running would orphan the previous keys/float.
if (existsSync(path.join(ROOT, '.env'))) {
  console.error('ERROR: .env already exists. Delete it manually to reset (testnet keys will be orphaned).');
  process.exit(1);
}

console.log('=== NordStern Anchor Template — Testnet Setup (INR <> USDC) ===\n');

// --- Step 1: keypairs (no issuer — Circle issues USDC) ---
console.log('Step 1: Generating keypairs...');
const signing  = Keypair.random();
const treasury = Keypair.random();
console.log(`  Signing:  ${signing.publicKey()}`);
console.log(`  Treasury: ${treasury.publicKey()}`);

// --- Step 2: fund with XLM via Friendbot ---
console.log('\nStep 2: Funding accounts via Friendbot...');
async function fund(kp, label) {
  const res = await fetch(`${FRIENDBOT_URL}?addr=${kp.publicKey()}`);
  if (!res.ok) throw new Error(`Friendbot failed for ${label}: ${await res.text()}`);
  console.log(`  Funded ${label}`);
}
await fund(signing, 'signing');
await fund(treasury, 'treasury');

console.log('\n  Waiting for ledger confirmation...');
await new Promise(r => setTimeout(r, 5000));

// --- Step 3: treasury trusts USDC (so it can hold the float) ---
console.log(`\nStep 3: Adding USDC trustline to treasury (issuer ${USDC_ISSUER.slice(0, 8)}...)...`);
const usdc = new Asset(ASSET_CODE, USDC_ISSUER);
const treasuryAccount = await server.loadAccount(treasury.publicKey());
const trustTx = new TransactionBuilder(treasuryAccount, { fee: BASE_FEE, networkPassphrase: NETWORK_PASSPHRASE })
  .addOperation(Operation.changeTrust({ asset: usdc, limit: '10000000' }))
  .setTimeout(30)
  .build();
trustTx.sign(treasury);
await server.submitTransaction(trustTx);
console.log('  Trustline created: treasury trusts USDC (balance 0 — float funding is Phase B)');

// --- Step 4: render config templates ---
console.log('\nStep 4: Rendering config/stellar.toml and config/assets.yaml...');
function render(templateName, outName, subs) {
  const tpl = readFileSync(path.join(CONFIG_DIR, templateName), 'utf8');
  const out = Object.entries(subs).reduce((s, [k, v]) => s.replaceAll(k, v), tpl);
  writeFileSync(path.join(CONFIG_DIR, outName), out);
  console.log(`  Wrote config/${outName}`);
}
render('stellar.toml.template', 'stellar.toml', { __SIGNING_PUBLIC__: signing.publicKey() });
render('assets.yaml.template',  'assets.yaml',  { __TREASURY_PUBLIC__: treasury.publicKey() });

// --- Step 5: write .env ---
console.log('\nStep 5: Writing .env...');
const env = [
  '# NordStern Anchor Template — generated by scripts/setup-testnet.mjs. DO NOT COMMIT.',
  '',
  `ASSET_CODE=${ASSET_CODE}`,
  `ASSET_ISSUER_PUBLIC=${USDC_ISSUER}`,
  `HORIZON_URL=${HORIZON_URL}`,
  `NETWORK_PASSPHRASE=${NETWORK_PASSPHRASE}`,
  '',
  `SIGNING_PUBLIC=${signing.publicKey()}`,
  `SIGNING_SECRET=${signing.secret()}`,
  `TREASURY_PUBLIC=${treasury.publicKey()}`,
  `TREASURY_SECRET=${treasury.secret()}`,
  '',
  `SEP10_JWT_SECRET=${rand()}`,
  `SEP24_INTERACTIVE_JWT_SECRET=${rand()}`,
  `SEP24_MORE_INFO_JWT_SECRET=${rand()}`,
  `SEP6_MORE_INFO_JWT_SECRET=${rand()}`,
  '',
  'DB_USER=anchor',
  'DB_PASSWORD=anchor',
  '',
  'KYC_PROVIDER=mock',
  'FEE_PROVIDER=live',
  'DEPOSIT_PROVIDER=mock',
  'PAYOUT_PROVIDER=mock',
  '',
].join('\n');
writeFileSync(path.join(ROOT, '.env'), env, { mode: 0o600 });
console.log('  Wrote .env (permissions 600)');

console.log('\n=== Setup complete ===');
console.log(`\n  Asset:    USDC:${USDC_ISSUER}`);
console.log(`  Treasury: ${treasury.publicKey()} (USDC balance 0 — fund the float in Phase B)`);
console.log('\nNext: docker compose up --build');
