items:
  - id: "stellar:ANCH:GB77U3E3A3Q5D3ILYYP6TM2XU5VUCTKPCXB4UAOK4LRXYTKCOA6XMA4D"
    distribution_account: "GCJHSFJETWDJNK2MDUWSBQA6P6VC4K4WOTKL6F5GTP4EDDUUF6GGWA6M"
    significant_decimals: 2
    sep24:
      enabled: true
      deposit:
        enabled: true
        min_amount: 1
        max_amount: 1000000
        methods: []
      withdraw:
        enabled: true
        min_amount: 1
        max_amount: 1000000
        methods: []
